### ISSUE TITLE
Browser history navigation issue

### ISSUE THREAD

**Issue by eirikhm** [christianalfoni/jsfridge#1]
This is not a big issue, but it seems like the history handling is a bit off.
1. Open some website X
2. Open http://www.jsfridge.com/
3. I need to click browser back twice before I'm back on site X

Also:
1. Open http://www.jsfridge.com/
2. Select a course (ie "Welcome to the BETA")
3. Click browser back, I'm now stuck on jsfridge, and I cannot get back to the first page with course overview.

Keep up the good work!

**Comment by christianalfoni** [comment]
Hi Eirik!

Thansk for the feedback ;-)

It is an issue with the jFlux framework. Will go ahead and fix that right now! Thanks for the report!

**Comment by christianalfoni** [comment]
Okay, launched new version and should be okay now :-)
